### ISSUE TITLE
Missing "target_link_uri" param

### ISSUE THREAD

**Issue by kistoth90** [dmitry-viskov/pylti1.3-flask-example#20]
I tried to use the flask example, but after I set everything up I got an _Exception: Missing "target_link_uri" param_ error, when I call the /login [get] endpoint. For some reason the flask_request does not contains the 'target_link_uri'

```
@app.route('/login/', methods=['GET', 'POST'])
def login():
    tool_conf = ToolConfJsonFile(get_lti_config_path())
    launch_data_storage = get_launch_data_storage()

    flask_request = FlaskRequest()
    target_link_uri = flask_request.get_param('target_link_uri')
    if not target_link_uri:
        raise Exception('Missing "target_link_uri" param')

    oidc_login = FlaskOIDCLogin(flask_request, tool_conf, launch_data_storage=launch_data_storage)
    return oidc_login\
        .enable_check_cookies()\
        .redirect(target_link_uri)
```

Command line
``` Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 931-136-893
127.0.0.1 - - [12/Oct/2023 16:44:37] "GET /login HTTP/1.1" 308 -
127.0.0.1 - - [12/Oct/2023 16:44:37] "GET /login/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kistoth/.local/share/virtualenvs/pylti1.3-flask-example-pg7iwl7d/lib/python3.8/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kistoth/Asztal/pylti1.3-flask-example/game/app.py", line 25, in __call__
    return self.app(environ, start_response)
  File "/home/kistoth/.local/share/virtualenvs/pylti1.3-flask-example-pg7iwl7d/lib/python3.8/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kistoth/.local/share/virtualenvs/pylti1.3-flask-example-pg7iwl7d/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kistoth/.local/share/virtualenvs/pylti1.3-flask-example-pg7iwl7d/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kistoth/.local/share/virtualenvs/pylti1.3-flask-example-pg7iwl7d/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kistoth/.local/share/virtualenvs/pylti1.3-flask-example-pg7iwl7d/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kistoth/Asztal/pylti1.3-flask-example/game/app.py", line 92, in login
    raise Exception('Missing "target_link_uri" param')
Exception: Missing "target_link_uri" param

**Comment by kistoth90** [comment]
It was my fault. The /login has been called by the LTM. I cannot call that endpoint trough postman...

**Comment by kistoth90** [comment]
Not valid issue
